import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Crop, Download, FlipHorizontal, FlipVertical, RotateCcw, RotateCw, Sparkles, UploadCloud } from 'lucide-react';
import './styles.css';
import './extra.css';
import './mobile.css';
import './integrated.css';

type Tool = 'merge' | 'resize' | 'editor';
type Page = Tool | 'about' | 'terms' | 'privacy';
const presets = [['正方形', 1080, 1080], ['Instagram', 1080, 1350], ['ストーリー', 1080, 1920], ['YouTube', 1280, 720], ['X投稿', 1200, 675]] as const;
const imageUrl = (file: File) => URL.createObjectURL(file);
const loadImage = (url: string) => new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = url; });

function Drop({ accept, multiple = false, onFiles, label }: { accept: string; multiple?: boolean; onFiles: (files: File[]) => void; label: string }) {
  const ref = useRef<HTMLInputElement>(null);
  const pick = (files: FileList | File[]) => onFiles(Array.from(files));
  return <div className="drop compact" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); pick(e.dataTransfer.files); }} onClick={() => ref.current?.click()}>
    <UploadCloud /><b>{label}</b><input ref={ref} hidden type="file" accept={accept} multiple={multiple} onChange={e => e.target.files && pick(e.target.files)} />
  </div>;
}

function Merge() {
  const [files, setFiles] = useState<string[]>([]); const [direction, setDirection] = useState<'vertical' | 'horizontal'>('vertical'); const [gap, setGap] = useState(0);
  const [preview, setPreview] = useState('');
  const add = (items: File[]) => setFiles(current => [...current, ...items.filter(file => file.type.startsWith('image/')).map(imageUrl)]);
  useEffect(() => { let active = true; if (!files.length) { setPreview(''); return; } Promise.all(files.map(loadImage)).then(images => { const vertical = direction === 'vertical'; const width = vertical ? Math.max(...images.map(i => i.width)) : images.reduce((n, i) => n + i.width, 0) + gap * (images.length - 1); const height = vertical ? images.reduce((n, i) => n + i.height, 0) + gap * (images.length - 1) : Math.max(...images.map(i => i.height)); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d')!; ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, width, height); let offset = 0; images.forEach(image => { ctx.drawImage(image, vertical ? (width - image.width) / 2 : offset, vertical ? offset : (height - image.height) / 2); offset += (vertical ? image.height : image.width) + gap; }); if (active) setPreview(canvas.toDataURL('image/png')); }); return () => { active = false; }; }, [files, direction, gap]);
  const save = () => preview && download(preview, 'merged.png');
  return <section className="tool-card"><h2>画像結合</h2><p className="hint">複数の画像を縦または横に並べて1枚にします。</p><div className="settings"><div className="segmented"><button className={direction === 'vertical' ? 'selected' : ''} onClick={() => setDirection('vertical')}>縦方向</button><button className={direction === 'horizontal' ? 'selected' : ''} onClick={() => setDirection('horizontal')}>横方向</button></div><label>画像間の間隔：{gap}px<input className="range" type="range" min="0" max="100" value={gap} onChange={e => setGap(+e.target.value)} /></label></div><Drop accept="image/*" multiple onFiles={add} label="画像をドロップまたは選択" />{files.length > 0 && <><div className="merge-grid">{files.map(url => <img src={url} key={url} />)}</div><h3 className="preview-title">結合後のプレビュー</h3>{preview ? <img className="merge-preview" src={preview} alt="結合後のプレビュー" /> : <p className="hint">プレビューを作成中です…</p>}<button className="download full" disabled={!preview} onClick={save}><Download />1枚に結合して保存</button></>}</section>;
}

function Resize() {
  const [src, setSrc] = useState(''); const [width, setWidth] = useState(0); const [height, setHeight] = useState(0); const [format, setFormat] = useState('image/png');
  const add = async (files: File[]) => { const file = files.find(item => item.type.startsWith('image/')); if (!file) return; const url = imageUrl(file); const image = await loadImage(url); setSrc(url); setWidth(image.width); setHeight(image.height); };
  const save = async () => { const image = await loadImage(src); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d')!.drawImage(image, 0, 0, width, height); download(canvas.toDataURL(format, .9), `resized.${format === 'image/jpeg' ? 'jpg' : format === 'image/webp' ? 'webp' : 'png'}`); };
  return <section className="tool-card"><h2>画像リサイズ</h2><p className="hint">用途に合わせたサイズへ変更できます。</p><Drop accept="image/*" onFiles={add} label={src ? '画像を変更' : '画像をドロップまたは選択'} /><div className="preset-row">{presets.map(([name, w, h]) => <button key={name} onClick={() => { setWidth(w); setHeight(h); }}>{name}<small>{w}×{h}</small></button>)}</div><div className="dimensions"><label>幅<input type="number" min="1" value={width || ''} placeholder="幅" onChange={e => setWidth(+e.target.value)} /></label><label>高さ<input type="number" min="1" value={height || ''} placeholder="高さ" onChange={e => setHeight(+e.target.value)} /></label></div>{src && <><h3 className="preview-title">リサイズ後のプレビュー</h3><div className="resize-preview-box" style={{ aspectRatio: `${Math.max(width, 1)} / ${Math.max(height, 1)}` }}><img src={src} alt="リサイズ後のプレビュー" /></div></>}<label>保存形式<select value={format} onChange={e => setFormat(e.target.value)}><option value="image/png">PNG</option><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option></select></label><button className="download full" disabled={!src || width < 1 || height < 1} onClick={save}><Download />リサイズして保存</button></section>;
}

function Editor() {
  const [src, setSrc] = useState(''); const [format, setFormat] = useState('image/jpeg'); const [quality, setQuality] = useState(1); const [rotation, setRotation] = useState(0); const [flipX, setFlipX] = useState(false); const [flipY, setFlipY] = useState(false); const [crop, setCrop] = useState(false);
  const add = (files: File[]) => { const file = files.find(item => item.type.startsWith('image/')); if (file) setSrc(imageUrl(file)); };
  const save = async () => { if (!src) return; const image = await loadImage(src); const side = crop ? Math.min(image.width, image.height) : 0; const sw = crop ? side : image.width; const sh = crop ? side : image.height; const sx = crop ? (image.width - side) / 2 : 0; const sy = crop ? (image.height - side) / 2 : 0; const canvas = document.createElement('canvas'); const quarter = rotation % 180 !== 0; canvas.width = quarter ? sh : sw; canvas.height = quarter ? sw : sh; const ctx = canvas.getContext('2d')!; ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(rotation * Math.PI / 180); ctx.scale(flipX ? -1 : 1, flipY ? -1 : 1); ctx.drawImage(image, sx, sy, sw, sh, -sw / 2, -sh / 2, sw, sh); download(canvas.toDataURL(format, quality), `edited.${format === 'image/jpeg' ? 'jpg' : format === 'image/webp' ? 'webp' : 'png'}`); };
  return <section className="tool-card"><h2>画像編集・画像圧縮</h2><p className="hint">画像の容量を削減しながら、回転・反転・中央トリミング・形式変換ができます。</p><p className="compression-note">JPEGまたはWebPを選び、品質を下げるとファイルサイズをさらに小さくできます。品質100%なら画質を優先します。</p><Drop accept="image/*" onFiles={add} label={src ? '画像を変更' : '画像をドロップまたは選択'} />{src && <div className={crop ? 'editor-preview-frame cropped' : 'editor-preview-frame'}><img className="editor-preview" src={src} style={{ transform: `rotate(${rotation}deg) scale(${flipX ? -1 : 1},${flipY ? -1 : 1})` }} /></div>}<div className="editor-controls"><label>保存形式<select value={format} onChange={e => setFormat(e.target.value)}><option value="image/jpeg">JPEG（圧縮向け）</option><option value="image/webp">WebP（圧縮向け）</option><option value="image/png">PNG（画質優先）</option></select></label><label>品質：{Math.round(quality * 100)}%<input className="range" type="range" min=".1" max="1" step=".05" value={quality} onChange={e => setQuality(+e.target.value)} /></label><div className="action-grid"><button disabled={!src} onClick={() => setRotation((rotation + 270) % 360)}><RotateCcw />左回転</button><button disabled={!src} onClick={() => setRotation((rotation + 90) % 360)}><RotateCw />右回転</button><button disabled={!src} onClick={() => setFlipX(v => !v)}><FlipHorizontal />左右反転</button><button disabled={!src} onClick={() => setFlipY(v => !v)}><FlipVertical />上下反転</button><button disabled={!src} className={crop ? 'selected' : ''} onClick={() => setCrop(v => !v)}><Crop />中央トリミング</button></div></div><p className="editor-status">{crop ? '中央を正方形に切り抜く設定です。保存時に適用されます。' : '中央トリミングを押すと、中央の正方形だけを保存できます。'}</p><button className="download full" disabled={!src} onClick={save}><Download />圧縮・編集して保存</button></section>;
}

function download(data: string, name: string) { const a = document.createElement('a'); a.href = data; a.download = name; a.click(); }
function pathFor(page: Page) { return page === 'editor' ? '/image-tools/' : page === 'resize' ? '/image-resize/' : page === 'merge' ? '/image-merge/' : `/${page}/`; }
function Info({ page, go }: { page: 'about' | 'terms' | 'privacy'; go: (page: Page) => void }) { const content = page === 'about' ? ['サイトについて', 'toolboxは、画像結合・画像リサイズ・画像圧縮・画像編集をブラウザ内で利用できる無料の便利ツール集です。'] : page === 'terms' ? ['利用規約', '本サービスは無料で提供しています。利用者は自身が権利を持つ画像・動画のみを処理してください。処理は利用者の端末内で行われ、当サイトがファイルを保存することはありません。'] : ['プライバシーポリシー', '画像・動画はサーバーへアップロード・保存されません。ファイル処理は利用者の端末上のブラウザ内で行われます。当サイトではGoogle AdSenseによる広告を掲載し、広告配信のためCookieが使用される場合があります。']; return <section className="info-card"><p className="eyebrow">TOOLBOX / INFORMATION</p><h2>{content[0]}</h2><p>{content[1]}</p><button className="download" onClick={() => go('merge')}>ツールへ戻る</button></section>; }
function App() { const queryTool = new URLSearchParams(location.search).get('tool'); const initial: Page = queryTool === 'editor' || location.pathname.includes('image-tools') ? 'editor' : location.pathname.includes('image-resize') ? 'resize' : location.pathname.includes('about') ? 'about' : location.pathname.includes('terms') ? 'terms' : location.pathname.includes('privacy') ? 'privacy' : 'merge'; const [page, setPage] = useState<Page>(initial); const go = (next: Page) => { setPage(next); history.pushState({}, '', pathFor(next)); }; const info = page === 'about' || page === 'terms' || page === 'privacy'; return <><header><div className="brand"><span className="mark"><Sparkles size={18} /></span>toolbox</div><nav><button className={page === 'merge' ? 'active' : ''} onClick={() => go('merge')}>画像結合</button><button className={page === 'resize' ? 'active' : ''} onClick={() => go('resize')}>画像リサイズ</button><button className={page === 'editor' ? 'active' : ''} onClick={() => go('editor')}>画像編集</button></nav></header><main><h1>画像と動画を、かんたん編集。</h1><p className="lead">ファイルは外部に送信せず、ブラウザ内で処理します。</p>{info ? <Info page={page} go={go} /> : <><section className="privacy-hero"><Sparkles /><strong>画像・動画はサーバーに保存されません</strong></section>{page === 'merge' ? <Merge /> : page === 'resize' ? <Resize /> : <Editor />}</>}</main><footer><button onClick={() => go('about')}>サイトについて</button><button onClick={() => go('terms')}>利用規約</button><button onClick={() => go('privacy')}>プライバシーポリシー</button></footer></>; }
createRoot(document.getElementById('root')!).render(<App />);
